spring.application.name=first-project
spring.ai.google.genai.project-id=gemini-chatbot-vedant
spring.ai.google.genai.location=us-central1
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.5
server.port=8081